extra_data = {'translation': [['desafío', 'challenge', None, None, 10], [None, None, None, 'ˈCHalənj']],
              'all-translations': [['sustantivo', ['reto', 'desafío', 'desafiador'],
                                    [['reto', ['challenge', 'dare', 'daring'], None, 0.63563865, 'el'],
                                     ['desafío', ['challenge', 'defiance', 'dare', 'duel', 'daring'], None, 0.30978554,
                                      'el'], ['desafiador', ['challenger', 'challenge'], None, 9.315461e-05, 'el']],
                                    'challenge', 1], ['verbo', ['desafiar', 'impugnar', 'retar'], [
                  ['desafiar', ['challenge', 'defy', 'brave', 'dare', 'beard', 'outface'], None, 0.12913783],
                  ['impugnar', ['challenge', 'contest', 'impugn', 'oppose', 'refuse'], None, 0.057304565],
                  ['retar', ['challenge'], None, 0.026235942]], 'challenge', 2]], 'original-language': 'en',
              'possible-translations': [['challenge', None,
                                         [['desafío', 1000, True, False, [10]], ['reto', 1000, True, False, [2]],
                                          ['desafiar', 1000, True, False, [2]], ['impugnar', 1000, True, False, [2]],
                                          ['retar', 1000, True, False, [2]]], [[0, 9]], 'challenge', 0, 0]],
              'confidence': 0.83768755, 'possible-mistakes': None, 'language': [['en'], None, [0.83768755], ['en']],
              'synonyms': [['sustantivo', [[['dare', 'provocation', 'summons'], 'm_en_gbus0167500.006'], [
                  ['problem', 'difficult task', 'test', 'trial', 'trouble', 'bother', 'obstacle'],
                  'm_en_gbus0167500.009'], [['confrontation with', 'dispute with', 'stand against', 'test of',
                                             'opposition', 'disagreement with', 'questioning of', 'defiance',
                                             'ultimatum'], 'm_en_gbus0167500.012']], 'challenge', 1], ['verbo', [[[
                                                                                                                      'test',
                                                                                                                      'tax',
                                                                                                                      'try',
                                                                                                                      'strain',
                                                                                                                      'make demands on',
                                                                                                                      'weary',
                                                                                                                      'wear out',
                                                                                                                      'drain',
                                                                                                                      'sap',
                                                                                                                      'stretch',
                                                                                                                      'stimulate',
                                                                                                                      'arouse',
                                                                                                                      'inspire',
                                                                                                                      'excite',
                                                                                                                      'spur on'],
                                                                                                                  'm_en_gbus0167500.047'],
                                                                                                                 [[
                                                                                                                      'question',
                                                                                                                      'disagree with',
                                                                                                                      'object to',
                                                                                                                      'take exception to',
                                                                                                                      'confront',
                                                                                                                      'dispute',
                                                                                                                      'take issue with',
                                                                                                                      'protest against',
                                                                                                                      'call into question',
                                                                                                                      'demur about/against',
                                                                                                                      'dissent from',
                                                                                                                      'be a dissenter from'],
                                                                                                                  'm_en_gbus0167500.049']],
                                                                                                       'challenge', 2]],
              'definitions': [['sustantivo', [
                  ['a call to take part in a contest or competition, especially a duel.', 'm_en_gbus0167500.006',
                   'he accepted the challenge'],
                  ['an objection or query as to the truth of something, often with an implicit demand for proof.',
                   'm_en_gbus0167500.012', 'a challenge to the legality of the order'],
                  ['exposure of the immune system to pathogenic organisms or antigens.', 'm_en_gbus0167500.016',
                   'recently vaccinated calves should be protected from challenge', [None, None, ['Medicine']]]],
                               'challenge', 1], ['verbo', [
                  ['invite (someone) to engage in a contest.', 'm_en_gbus0167500.038',
                   'he challenged one of my men to a duel'],
                  ['dispute the truth or validity of.', 'm_en_gbus0167500.049',
                   "employees challenged the company's requirement"],
                  ['expose (the immune system) to pathogenic organisms or antigens.', 'm_en_gbus0167500.053', None,
                   [None, None, ['Medicine']]]], 'challenge', 2]], 'examples': [
        [['a <b>challenge</b> to the legality of the order', None, None, None, None, 'm_en_gbus0167500.012'],
         ['I heard the <b>challenge</b> “Who goes there?”', None, None, None, None, 'm_en_gbus0167500.013'],
         ['recently vaccinated calves should be protected from <b>challenge</b>', None, None, None, None,
          'm_en_gbus0167500.016'],
         ['the ridge is a <b>challenge</b> for experienced climbers', None, None, None, None, 'm_en_gbus0167500.009'],
         ['he needed something both to <b>challenge</b> his skills and to regain his crown as the king of the thriller',
          None, None, None, None, 'm_en_gbus0167500.047'],
         ['a world title <b>challenge</b>', None, None, None, None, 'm_en_gbus0167500.010'],
         ['he accepted the <b>challenge</b>', None, None, None, None, 'm_en_gbus0167500.006']]], 'see-also': None}
